from datetime import datetime
from sqlalchemy import String,Integer,DateTime,ForeignKey,Text,Boolean,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column,relationship
from database import Base
class User(Base):
 __tablename__='users'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(120)); email:Mapped[str]=mapped_column(String(255),unique=True,index=True); college_id:Mapped[str]=mapped_column(String(80)); password_hash:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Event(Base):
 __tablename__='events'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(200)); category:Mapped[str]=mapped_column(String(60)); description:Mapped[str]=mapped_column(Text); event_date:Mapped[str]=mapped_column(String(60)); venue:Mapped[str]=mapped_column(String(200)); starts_at:Mapped[datetime]=mapped_column(DateTime); ends_at:Mapped[datetime]=mapped_column(DateTime); fee_paise:Mapped[int]=mapped_column(Integer,default=0); capacity:Mapped[int]=mapped_column(Integer,default=500); image:Mapped[str]=mapped_column(String(255)); active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Registration(Base):
 __tablename__='registrations'; __table_args__=(UniqueConstraint('user_id','event_id',name='uq_user_event'),); id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); event_id:Mapped[int]=mapped_column(ForeignKey('events.id')); status:Mapped[str]=mapped_column(String(30),default='PENDING'); amount_paise:Mapped[int]=mapped_column(Integer); razorpay_order_id:Mapped[str|None]=mapped_column(String(100),nullable=True); razorpay_payment_id:Mapped[str|None]=mapped_column(String(100),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); confirmed_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); user=relationship('User'); event=relationship('Event'); pass_obj=relationship('EventPass',back_populates='registration',uselist=False,cascade='all,delete-orphan')
class EventPass(Base):
 __tablename__='event_passes'; id:Mapped[int]=mapped_column(primary_key=True); pass_uuid:Mapped[str]=mapped_column(String(36),unique=True,index=True); registration_id:Mapped[int]=mapped_column(ForeignKey('registrations.id'),unique=True); status:Mapped[str]=mapped_column(String(20),default='ISSUED'); scanned_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); scanned_by:Mapped[str|None]=mapped_column(String(100),nullable=True); registration=relationship('Registration',back_populates='pass_obj')
class Payment(Base):
 __tablename__='payments'; id:Mapped[int]=mapped_column(primary_key=True); registration_id:Mapped[int]=mapped_column(ForeignKey('registrations.id')); razorpay_order_id:Mapped[str]=mapped_column(String(100),unique=True); razorpay_payment_id:Mapped[str|None]=mapped_column(String(100),nullable=True); amount_paise:Mapped[int]=mapped_column(Integer); status:Mapped[str]=mapped_column(String(30),default='CREATED'); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class ScanLog(Base):
 __tablename__='scan_logs'; id:Mapped[int]=mapped_column(primary_key=True); pass_id:Mapped[str|None]=mapped_column(String(36),nullable=True); event_id:Mapped[int|None]=mapped_column(Integer,nullable=True); result:Mapped[str]=mapped_column(String(40)); gate:Mapped[str|None]=mapped_column(String(100),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
